# Generated by Django 4.1 on 2024-06-03 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieDisplay',
            fields=[
                ('display_id', models.AutoField(primary_key=True, serialize=False)),
                ('movie_name', models.CharField(blank=True, max_length=25, null=True)),
                ('image', models.FileField(upload_to='images/')),
            ],
        ),
    ]
